const PRIMARY = "#BB86FC";
const PRIMARY_VAR = "#3700B3";
const SECONDARY = "#03DAC6";
const BACKGROUND = "#242424";
const BLACK = "#000000";
const WHITE = "#FFFFFF";

export { PRIMARY, PRIMARY_VAR, SECONDARY, BACKGROUND, BLACK, WHITE };
